apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  namespace: qtul
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  namespace: veeg
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
