apiVersion: v1
kind: Service
metadata:
  labels:
    app: wmgd
    color: wmdg
    tier: wmgd
    type: wmgd
  name: nginx-lab-1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wmgd
    color: wmdg
    tier: wmgd
    type: wmgd
