apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod-2
spec:
  volumes:
  - name: log
    emptyDir: {}

  containers:
  - name: app
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/date.txt; sleep 80; done"]
    volumeMounts:
    - name: log
      mountPath: /var/log

  - name: sidecar
    image: centos/httpd
    ports:
    - containerPort: 80
    volumeMounts:
    - name: log
      mountPath: /var/www/html
